baseURL = "https://www.andreascalco.com/""
#baseURL = "https://eloquent-rosalind-65a526.netlify.app/"
languageCode = "en-us"
theme = "raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  # HEADER

#  [[menu.header]]
#  name = "About"
#  URL = "#about"
#  weight = 2

  [[menu.header]]
  name = "Experience & Education "
  URL = "#experience"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

    [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[menu.header]]
  name = "Blog on Medium"
  URL = "https://andrea-scalco.medium.com/"
  weight = 5



  # FOOTER

  [[menu.footer]]
  name = "Experience & Education "
  URL = "#experience"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[menu.footer]]
  name = "Blog on Medium"
  URL = "https://andrea-scalco.medium.com/"
  weight = 5



[params]

  #sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
  sections = ["showcase",  "experience", "education", "client-and-work", "contact"]

  googleTagManagerID = "GTM-KQBZ6GG" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "andrea"
    text2 = "scalco"

  [params.footer]
      copyright = 'Built with Hugo | Theme by Radity | Deployed on Netlify'

      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
